### ISSUE TITLE
Run Error: ModuleNotFoundError: No module named 'frontend'

### ISSUE THREAD

**Issue by bliubiu** [StuHude/PDF-Watermark-Removal#1]
PDF-Watermark-Removal>python app.py
Traceback (most recent call last):
  File "D:\Training\studypy\pdf\PDF-Watermark-Removal\app.py", line 5, in <module>
    import fitz
  File "C:\Upgs\Python\python3\lib\site-packages\fitz\__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'

**Comment by dpzain** [comment]
same as u , resolved?

**Comment by zicai-danhuatang** [comment]
you can do `pip install PyMuPDF` to solves this problem
